---
datadog:
  clusterName: raccoon
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
  kubelet:
    tlsVerify: false
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
    autoMultiLineDetection: true
  apm:
    portEnabled: true
  processAgent:
    enabled: true
    processCollection: true
  helmCheck:
    enabled: true
    collectEvents: true
  networkMonitoring:
    enabled: false
  containerExclude: image:gcr.io/datadoghq/.*
