version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      timezone: America/Los_Angeles
      interval: weekly
      day: monday
      time: "09:00"
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20

  - package-ecosystem: terraform
    directory: core
    schedule:
      timezone: America/Los_Angeles
      interval: weekly
      day: monday
      time: "09:00"
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20

  - package-ecosystem: terraform
    directory: stack
    schedule:
      timezone: America/Los_Angeles
      interval: weekly
      day: monday
      time: "09:00"
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20

  - package-ecosystem: terraform
    directory: kubernetes
    schedule:
      timezone: America/Los_Angeles
      interval: weekly
      day: monday
      time: "09:00"
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20

  - package-ecosystem: terraform
    directory: gke
    schedule:
      timezone: America/Los_Angeles
      interval: weekly
      day: monday
      time: "09:00"
    commit-message:
      prefix: build
      include: scope
    open-pull-requests-limit: 20
