---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: 0 */2 * * *
    assignees:
      - acchiao

  - package-ecosystem: terraform
    directory: core
    schedule:
      interval: cron
      cronjob: 0 */2 * * *
    assignees:
      - acchiao

  - package-ecosystem: terraform
    directory: stack
    schedule:
      interval: cron
      cronjob: 0 */2 * * *
    assignees:
      - acchiao

  - package-ecosystem: terraform
    directory: kubernetes
    schedule:
      interval: cron
      cronjob: 0 */2 * * *
    assignees:
      - acchiao

  - package-ecosystem: terraform
    directory: gke
    schedule:
      interval: cron
      cronjob: 0 */2 * * *
    assignees:
      - acchiao
