---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "core"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "stack"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "kubernetes"
    schedule:
      interval: "daily"
