---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0  # frozen: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: sort-simple-yaml
      - id: check-yaml

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 57467c56d491420aa6c89f722b120ac7bea0289b  # frozen: v1.73.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-diff
          - --args=-write=true
      - id: terraform_providers_lock
      - id: terraform_validate

  - repo: https://github.com/adrienverge/yamllint.git
    rev: a09ad89268e9042349b764084426617da69957d3  # frozen: v1.27.1
    hooks:
      - id: yamllint
